name: CI

on:
  schedule:
    - cron:  '0 0 * * 1'
  push:
    branches:
    - action
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build archlinux package
        uses: countstarlight/arch-makepkg-action@master
        with:
          packages: >
            p7zip
            wine
            wine-mono
            wine-gecko
            xorg-xwininfo
            wqy-microhei
            lib32-alsa-lib
            lib32-alsa-plugins
            lib32-libpulse
            lib32-openal
            lib32-mpg123
            lib32-gnutls
          scripts: "makepkg && ./gen.sh -m"
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: deepin-wine-qq*.pkg*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
